name: Kirpal Demian
firstname: Kirpal
description: >-
  I'm a software engineer working with Flutter for cross-platform development. Besides 
  coding, I love cooking ğŸ, reading ğŸ“–, hiking ğŸ¥¾, camping ğŸ•ï¸, biking ğŸš´, and skiing â›·ï¸.

url: "https://kirp.al"
github_username:  kirpal

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      inline_styles:
        - post.scss
      linked_styles:
        - tango.css
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed
